name: Maven Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    strategy:
      matrix:
        service:
          - coursemanagement
          - courserecommendation
          - courseregistration
          - notificationservice
          - usermanagement
        include:
          - service: coursemanagement
            db_name: course_db
          - service: courserecommendation
            db_name: recommendation_db
          - service: courseregistration
            db_name: registration_db
          - service: notificationservice
            db_name: notification_db
          - service: usermanagement
            db_name: user_management_db

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password123
          MYSQL_DATABASE: ${{ matrix.db_name }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Run Unit & Integration Tests with H2
        working-directory: ./${{ matrix.service }}
        run: mvn test -Dspring.batch.job.enabled=false
        env:
          SPRING_PROFILES_ACTIVE: test
          # No need to pass MySQL credentials — H2 will be used
          # H2 settings are read from application-test.properties or application.properties via spring.profiles.active

      - name: Build and Package (main branch only)
        if: github.ref == 'refs/heads/main'
        working-directory: ./${{ matrix.service }}
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload Build Artifact (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-artifact
          path: ./${{ matrix.service }}/target/*.jar
          retention-days: 3

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: failure() # Only upload detailed reports on failure
        with:
          name: ${{ matrix.service }}-test-reports
          path: |
            ${{ matrix.service }}/target/surefire-reports/
            ${{ matrix.service }}/target/failsafe-reports/
          retention-days: 3
