# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        service: 
          - coursemanagement
          - courserecommendation
          - courseregistration
          - notificationservice
          - usermanagement
  
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'


    - name: Build ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: mvn -B package --file pom.xml
    
    - name: Run Unit Tests for ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: mvn test
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-artifact
        path: ${{ matrix.service }}/target/*.jar
          


